[Fireball0]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball1]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball2]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball3]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball4]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball5]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball6]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball7]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball8]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball9]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball10]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball11]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball12]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball13]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball14]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball15]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball16]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball17]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball18]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball19]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball20]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball21]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball22]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball23]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball24]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball25]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball26]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball27]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball28]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball29]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball30]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball31]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball32]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball33]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball34]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball35]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball36]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball37]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball38]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball39]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball40]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball41]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball42]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball43]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball44]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball45]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball46]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball47]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball48]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
    
[Fireball49]
    type="item"
    image="fire/carl-olsen/flame.png"
    description="Ball made of fire. Throw 2k10 for damage."
    icons=""
    filter=""
